Add ability to read cipher key from Secret Manager
statisticsnorway/dapla-statbank-authenticator pull request #1
Opened 2022-09-27 09:37 UTC by bjornandre

This PR supports the Secret Manager pattern from the [Berglas environment variable reference syntax](https://github.com/GoogleCloudPlatform/berglas/blob/main/doc/reference-syntax.md).

2022-09-27 12:50 UTC, mmwinther requested changes

2022-09-27 12:50 UTC, mmwinther commented on app/main.py
> +    if "#" in splitted[1]:
This is slightly cryptic, could have a short comment on what we're checking here

2022-09-27 12:50 UTC, mmwinther commented on tests/test_api.py
> +def test_parsing():
This looks like two tests to me

2022-09-27 12:50 UTC, mmwinther commented on app/main.py
> +    if os.environ['CIPHER_KEY'].startswith(SECRET_MANAGER_PREFIX):
Should we not raise an EnvironmentError if this check fails? Or does that mean we've already decoded the key? In that case, would be good to have a comment.

2022-09-27 12:50 UTC, mmwinther commented on app/main.py
> +            logger.error("Data corruption detected.", response)
Shouldn't we raise an exception in this case as well? Otherwise we'll just continue on

2022-09-27 12:54 UTC, mmwinther commented on app/main.py
> +    if os.environ['CIPHER_KEY'].startswith(SECRET_MANAGER_PREFIX):
I think it's worth writing a test for this code block, looks like it's doable by mocking `access_secret_version`

2022-09-28 15:44 UTC, bjornandre commented on app/main.py
> +    if "#" in splitted[1]:
Fixed

2022-09-28 15:44 UTC, bjornandre commented on app/main.py
> +            logger.error("Data corruption detected.", response)
Fixed

2022-09-28 18:58 UTC, bjornandre commented on app/main.py
> +    if os.environ['CIPHER_KEY'].startswith(SECRET_MANAGER_PREFIX):
Fixed

2022-09-28 19:00 UTC, bjornandre commented on app/main.py
> +    if os.environ['CIPHER_KEY'].startswith(SECRET_MANAGER_PREFIX):
The cipher key can either be stored directly in the environment variable, or via Secret Manager. Added a comment.

2022-09-29 06:19 UTC, mmwinther approved these changes
Great structure and tests 👍

2022-09-29 06:19 UTC, mmwinther commented on tests/test_api.py
> +app.dependency_overrides[get_sm_client] = lambda: sm_client
This was clever 👍

2022-09-29 06:21 UTC, merged